function marqueeInit(k){document.createElement&&(marqueeInit.ar.push(k),marqueeInit.run(k.uniqueid))}
(function(){function k(a){for(var c=[],b=0,d;(d=a.firstChild)&&3===d.nodeType&&h[0].test(d.nodeValue);)a.removeChild(d);for(;(d=a.lastChild)&&3===d.nodeType&&h[0].test(d.nodeValue);)a.removeChild(d);(d=a.firstChild)&&3===d.nodeType&&(d.nodeValue=d.nodeValue.replace(h[1],""));(d=a.lastChild)&&3===d.nodeType&&(d.nodeValue=d.nodeValue.replace(h[2],""));for(;d=a.firstChild;)c[b++]=a.removeChild(d);return c}function n(a){for(var c=a.getElementsByTagName("*"),b=c.length,d=[];-1<--b;)c[b].parentNode===a&&
d.push(c[b]);d.sort(function(){return.5-Math.random()});for(b=d.length;-1<--b;)a.appendChild(d[b])}function g(a,c){var b,d,f,g,e,l,m=this;this.mq=marqueeInit.ar[a];this.mq.random&&(c.getElementsByTagName&&1===c.getElementsByTagName("tr").length&&1===c.childNodes.length?n(c.getElementsByTagName("tr")[0]):n(c));for(b in p)if(this.mq.hasOwnProperty&&!this.mq.hasOwnProperty(b)||!this.mq.hasOwnProperty&&!this.mq[b])this.mq[b]=p[b];this.mq.direction=this.mq.persist&&this.cookie.get(this.mq.uniqueid)?this.cookie.get(this.mq.uniqueid).split(":")[2]:
this.mq.direction;this.mq.style.width=!this.mq.style.width||isNaN(parseInt(this.mq.style.width))?"100%":this.mq.style.width;c.getElementsByTagName("img")[0]?this.mq.style.height=!this.mq.style.height||isNaN(parseInt(this.mq.style.height))?"auto":this.mq.style.height:this.mq.style.height=!this.mq.style.height||isNaN(parseInt(this.mq.style.height))?c.offsetHeight+3+"px":this.mq.style.height;d=this.mq.style.width.split(/\d/);this.cw=this.mq.style.width?[parseInt(this.mq.style.width),d[d.length-1]]:["a"];
l=k(c);c.className=c.id="";c.removeAttribute("class",0);c.removeAttribute("id",0);c.appendChild(c.cloneNode(!1));c.className=["marquee",a].join("");c.style.overflow="hidden";this.c=c.firstChild;this.c.appendChild(this.c.cloneNode(!1));this.c.style.visibility="hidden";d=[[u,this.c.style],[this.mq.style,this.c.style]];for(e=d.length-1;-1<e;--e)for(b in d[e][0])if(d[e][0].hasOwnProperty&&d[e][0].hasOwnProperty(b)||!d[e][0].hasOwnProperty)d[e][1][b.encamel()]=d[e][0][b];this.m=this.c.firstChild;"pause"===
this.mq.mouse&&(this.c.onmouseover=function(){m.mq.stopped=!0},this.c.onmouseout=function(){m.mq.stopped=!1});this.m.style.position="absolute";this.m.style.left="-10000000px";this.m.style.whiteSpace="nowrap";this.mq.noAddedSpace||this.m.appendChild(document.createTextNode("\u00a0"));for(e=0;l[e];++e)this.m.appendChild(l[e]);f=this.m.getElementsByTagName("img");if(f.length)for(e=g=0;e<f.length;++e)f[e].style.display="inline",f[e].alt||this.mq.noAddedAlt||(f[e].alt=h[3].exec(f[e].src)||"Image #"+[e+
1],f[e].title||(f[e].title="")),f[e].style.display="inline",f[e].style.verticalAlign=f[e].style.verticalAlign||"top","boolean"===typeof f[e].complete&&f[e].complete?g++:f[e].onload=f[e].onerror=function(){++g===f.length&&m.setup(a)},g===f.length&&this.setup(a);else this.setup(a)}function q(){for(var a,c,b,d=0;d<marqueeInit.ar.length;++d)if(marqueeInit.ar[d]&&marqueeInit.ar[d].setup)for(b=marqueeInit.ar[d].setup,a=b.mq.moveatleast?Math.max(b.mq.moveatleast,b.sinc):b.sinc||b.mq.inc,b.c.style.width=
b.mq.style.width,b.cw[0]=1<b.cw.length?parseInt(b.mq.style.width):"a";b.c.offsetWidth>b.w-a;){c=isNaN(b.cw[0])?b.w-a:--b.cw[0];if(1>c)break;b.c.style.width=isNaN(b.cw[0])?b.w-a+"px":--b.cw[0]+b.cw[1]}}function r(){for(var a,c=0;c<marqueeInit.ar.length;++c)marqueeInit.ar[c]&&marqueeInit.ar[c].persist&&marqueeInit.ar[c].setup&&(a=marqueeInit.ar[c].setup,a.cookie.set(a.mq.uniqueid,a.m[0].style.left+":"+a.m[1].style.left+":"+a.mq.direction))}if(document.createElement){"undefined"===typeof opera&&(window.opera=
!1);marqueeInit.ar=[];document.write('<style type="text/css">.marquee{white-space:nowrap;overflow:hidden;visibility:hidden;}#marq_kill_marg_bord{border:none!important;margin:0!important;}</style>');var v=0,h=[/^\s*$/,/^\s*/,/\s*$/,/[^\/]+$/],u={position:"relative",overflow:"hidden"},p={style:{margin:"0 auto"},direction:"left",inc:2,mouse:"pause"},t,w=function(a,c){return c.toUpperCase()};t=/-(.)/g;String.prototype.encamel=function(){return this.replace(t,w)};marqueeInit.run=function(a){document.getElementById(a)?
new g(v++,document.getElementById(a)):setTimeout(function(){marqueeInit.run(a)},300)};g.prototype.setup=function(a){if(!this.mq.setup){this.mq.setup=this;var c,b=this,d=1E4;"auto"===this.c.style.height&&(this.c.style.height=this.m.offsetHeight+4+"px");this.c.appendChild(this.m.cloneNode(!0));this.m=[this.m,this.m.nextSibling];"function"===typeof this.mq.initcontent&&this.mq.initcontent.apply(this.mq,[this.m]);"cursor driven"===this.mq.mouse&&(this.r=this.mq.neutral||16,this.sinc=this.mq.inc,this.c.onmousemove=
function(a){b.mq.stopped=!1;b.directspeed(a)},this.mq.moveatleast?(this.mq.inc=this.mq.moveatleast,this.mq.savedirection?"reverse"===this.mq.savedirection?this.c.onmouseout=function(a){b.contains(a)||(b.mq.inc=b.mq.moveatleast,b.mq.direction="right"===b.mq.direction?"left":"right")}:(this.mq.savedirection=this.mq.direction,this.c.onmouseout=function(a){b.contains(a)||(b.mq.inc=b.mq.moveatleast,b.mq.direction=b.mq.savedirection)}):this.c.onmouseout=function(a){b.contains(a)||(b.mq.inc=b.mq.moveatleast)}):
this.c.onmouseout=function(a){b.contains(a)||b.slowdeath()});this.w=this.m[0].offsetWidth;this.m[0].style.left=this.mq.persist&&this.cookie.get(this.mq.uniqueid)?this.cookie.get(this.mq.uniqueid).split(":")[0]:0;this.c.id="marq_kill_marg_bord";this.m[0].style.top=this.m[1].style.top=Math.floor((this.c.offsetHeight-this.m[0].offsetHeight)/2-0)+"px";this.c.id="";this.c.removeAttribute("id",0);this.m[1].style.left=this.mq.persist&&this.cookie.get(this.mq.uniqueid)?this.cookie.get(this.mq.uniqueid).split(":")[1]:
this.w+"px";for(a=this.mq.moveatleast?Math.max(this.mq.moveatleast,this.sinc):this.sinc||this.mq.inc;this.c.offsetWidth>this.w-a&&--d;){c=isNaN(this.cw[0])?this.w-a:--this.cw[0];if(1>c||this.w<Math.max(1,a))break;this.c.style.width=isNaN(this.cw[0])?this.w-a+"px":--this.cw[0]+this.cw[1]}this.c.style.visibility="visible";this.runit()}};g.prototype.slowdeath=function(){var a=this;this.mq.inc&&(--this.mq.inc,this.timer=setTimeout(function(){a.slowdeath()},100))};g.prototype.runit=function(){var a=this,
c="right"===this.mq.direction?1:-1;this.mq.stopped||this.mq.stopMarquee?setTimeout(function(){a.runit()},300):("cursor driven"!=this.mq.mouse&&(this.mq.inc=Math.max(1,this.mq.inc)),c*parseInt(this.m[0].style.left)>=this.w&&(this.m[0].style.left=parseInt(this.m[1].style.left)-c*this.w+"px"),c*parseInt(this.m[1].style.left)>=this.w&&(this.m[1].style.left=parseInt(this.m[0].style.left)-c*this.w+"px"),this.m[0].style.left=parseInt(this.m[0].style.left)+c*this.mq.inc+"px",this.m[1].style.left=parseInt(this.m[1].style.left)+
c*this.mq.inc+"px",window.opera&&this.mq.persist&&this.cookie.set(this.mq.uniqueid,this.m[0].style.left+":"+this.m[1].style.left+":"+this.mq.direction),setTimeout(function(){a.runit()},30+(this.mq.addDelay||0)))};g.prototype.cookie={set:function(a,c,b){if(b){var d=new Date;d.setDate(d.getDate()+b);b="; expires="+d.toGMTString()}document.cookie=a+"="+escape(c)+(b||"")+"; path=/"},get:function(a){return(a=document.cookie.match("(^|;) *"+a+"=([^;]*)"))?unescape(a[2]):null},kill:function(a){cook.set(a,
"",-1)},killall:function(){var a=document.cookie.split(";"),c=a.length-1;for(c;-1<c;--c)cook.kill(a[c].split("=")[0])}};g.prototype.directspeed=function(a){a=a||window.event;this.timer&&clearTimeout(this.timer);var c=this.c,b=c.offsetWidth;a=("number"===typeof a.pageX?a.pageX:a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft)-c.offsetLeft;for(var d=(b-this.r)/2,b=(b+this.r)/2;c=c.offsetParent;)a-=c.offsetLeft;this.mq.direction=a>b?"left":"right";this.mq.inc=Math.round((a>b?a-
b:a<d?d-a:0)/d*this.sinc)};g.prototype.contains=function(a){if(a&&a.relatedTarget){a=a.relatedTarget;if(a===this.c)return!0;for(;a=a.parentNode;)if(a===this.c)return!0}return!1};window.addEventListener?(window.addEventListener("resize",q,!1),window.addEventListener("unload",r,!1)):window.attachEvent&&(window.attachEvent("onresize",q),window.attachEvent("onunload",r))}})();
